

version: 2
jobs:
  build:
    # working_directory: /tempo
    docker: 
      - image: circleci/node:6
    steps:
      - checkout
      - run: |
          sudo apt-get install -y asciidoctor
          asciidoctor getting-started.adoc
      - run: git clone git@github.com:witmicko/origin-web-console.git
      - run: |
          cp getting-started.html /app/views/mobile-client-sdk-config/
          grunt build

      

      