

version: 2
jobs:
  build:
    # working_directory: /tempo
    docker: 
      - image: circleci/node:6
    steps:
      - setup_remote_docker
      - checkout
      - run: ls && pwd
      - run: docker version
      - run: docker run asciidoctor/docker-asciidoctor asciidoctor getting-started.adoc

      