

version: 2
jobs:
  build:
    # working_directory: /tempo
    docker: 
      - image: circleci/node:6
    steps:
      - checkout
      - run: |
          sudo apt-get install -y asciidoctor
          asciidoctor getting-started.adoc
      - run: git clone git@github.com:aerogear/origin-web-console.git
      - run: cd origin-web-
      - run: pwd
      - run: git checkout origin/AEROGEAR-2265-Mobile_Client_Representation_View
      - run: cp ../getting-started.html /app/views/mobile-client-sdk-config/
      - run: cd origin-web-console
      - run: grunt build

      

      