defaults: &defaults
  working_directory: /repo

version: 2
jobs:
  once:
    <<: *defaults
    docker: 
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "hello world"
      - run: ls
      - run: pwd
  convertToHtml:
    <<: *defaults
    docker: 
      - image: asciidoctor/docker-asciidoctor
    steps:
      - checkout
      - run: pwd
      - run: asciidoctor getting-started.adoc 
      - run: ls
      - persist_to_workspace:
          root: .
          paths: getting-started.html
            - 
workflows:
  version: 2
  build:
    jobs:
      - convertToHtml
      - once:
          requires:
            - convertToHtml
      