

version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:6
    steps:
      - checkout
      - run: |
          sudo apt-get install -y asciidoctor
          asciidoctor getting-started.adoc
      - run: git clone git@github.com:aerogear/origin-web-console.git
      - run: |
          cd origin-web-console && 
          pwd &&
          git checkout origin/AEROGEAR-2265-Mobile_Client_Representation_View
      - run: cp getting-started.html origin-web-console/app/views/mobile-client-sdk-config/
      - run: cd origin-web-console && npm i && sudo npm i -g grunt-cli && grunt build
      - run: |
          cd origin-web-console &&
          git add --all &&
          git commit -m "yolo" &&
          git remote add mick git@github.com:witmicko/origin-web-console.git
          git push mick AEROGEAR-2265-Mobile_Client_Representation_View

      

      