

version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: install asciidoc and convert 
          command: |
            sudo apt-get install -y asciidoctor
            asciidoctor getting-started.adoc
      - run: 
          name: clone aerogear/origin-web-console
          command: |
            # git clone git@github.com:aerogear/origin-web-console.git
            git clone https://github.com/witmicko/origin-web-console.git
      - run: 
          name: copy html into console and build 
          command: |
            cp getting-started.html origin-web-console/app/views/
            # cp getting-started.html origin-web-console/app/views/mobile-client-sdk-config/
            # npm i && sudo npm i -g grunt-cli && grunt build
            # this is temporary, should be working of master
    
      - run: 
          name: git status 
          command: |
            cd origin-web-console &&
            git status -s
      - run: 
          name: setup git user and remote 
          command: |
            cd origin-web-console &&
            git config user.email "something@ff.ff" &&
            git config user.name "somename"
      - run: 
          name: git add all 
          command: |
            cd origin-web-console &&
            git add --all
      - run: 
          name: git commit
          command: |
            cd origin-web-console &&
            git checkout -b docs_update &&
            git commit -m "yolo"
      - run: 
          name: git status
          command: |
            cd origin-web-console &&
            git status -s  
      - run: 
          name: git push 
          command: |
            cd origin-web-console &&
            git remote -v &&
            git push origin docs_update 

      

      