defaults: &defaults
  working_directory: /repoasda

version: 2
jobs:
  once:
    <<: *defaults
    docker: 
      - image: circleci/node:6
    steps:
      - attach_workspace:
          at: /repoasda/workspace
      - run: ls
      - run: pwd
      - git clone git@github.com:witmicko/origin-web-console.git
      - run: ls
  convertToHtml:
    <<: *defaults
    docker: 
      - image: asciidoctor/docker-asciidoctor
    steps:
      - run: pwd
      - run: ls
      - checkout
      - run: pwd
      - run: asciidoctor getting-started.adoc
      - run: mkdir -p workspace
      - run: mv getting-started.html workspace/getting-started.html
      - run: ls
      - persist_to_workspace:
          root: workspace
          paths:
              - getting-started.html
workflows:
  version: 2
  build:
    jobs:
      - convertToHtml
      - once:
          requires:
            - convertToHtml
      